title: AI Perspectives
email: your-email@example.com
description: >-
  Exploring the cutting edge of artificial intelligence and its impact on our world.
baseurl: "/githubpagestoy" # the subpath of your site, e.g. /blog
url: "https://ehippy.github.io" # Your GitHub username
github_username: ehippy # Your GitHub username

# Social media
# Removed as not currently used

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
  - CNAME
  - .git/
  - .gitignore
