title: GitHub Pages Toy
email: your-email@example.com
description: >-
  A simple Jekyll site that publishes to GitHub Pages.
baseurl: "/githubpagestoy" # the subpath of your site, e.g. /blog
url: "https://ehippy.github.io" # Your GitHub username
github_username: ehippy # Your GitHub username

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
