title: AI Perspectives
email: your-email@example.com
description: >-
  Exploring the cutting edge of artificial intelligence and its impact on our world.
baseurl: "/githubpagestoy" # the subpath of your site, e.g. /blog
url: "https://ehippy.github.io" # Your GitHub username/organization url
github_username: ehippy # Your GitHub username
author: AI Perspectives Team

# SEO settings
twitter:
  username: # Add your Twitter username if available
  card: summary_large_image
logo: /assets/images/logo.png # Path to your site logo (create this if needed)
social:
  name: AI Perspectives
  links:
    - https://github.com/ehippy/githubpagestoy

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Performance and optimization
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [development]
  blanklines: false
  profile: false
  startings: [html, head, body]

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/articles/:title/"
      author: "AI Perspectives Team"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
  - CNAME
  - .git/
  - .gitignore
